services:
  backend:
    build: .
    ports:
      - "8443:8443"
    network_mode: "host"
    environment:
      - JINA_API_KEY=${JINA_API_KEY}
      - MANUFACTURER_DB_DB=${MANUFACTURER_DB_DB}
      - MANUFACTURER_DB_USER=${MANUFACTURER_DB_USER}
      - MANUFACTURER_DB_PASSWORD=${MANUFACTURER_DB_PASSWORD}
      - MANUFACTURER_DB_HOST=${MANUFACTURER_DB_HOST}
      - MANUFACTURER_DB_PORT=${MANUFACTURER_DB_PORT}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always