#nvidia gpu support
services:
  backend:
    build: .
    ports:
      - "8443:8443"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/facecrime
      - JINA_API_KEY=${JINA_API_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/mnt/ssd/facecrime_mongodb
volumes:
  mongo-data:
